export const REDIS_OUTBOX_EVENT_TYPES = [
  'PRODUCT_PRICING_POLICY_CREATED',
  'AGENT_PRICING_OVERRIDE_CREATED',
  'AGENT_PRICING_OVERRIDE_CLOSED',
  'AGENT_RETAIL_PRICE_SET',
  'PAYMENT_INITIALIZATION_REQUESTED',
  'RESERVATION_EXPIRY_DUE',
  'PRODUCT_PRICING_POLICY_ACTIVATION_DUE',
  'AGENT_PRICING_OVERRIDE_ACTIVATION_DUE',
  'REFUND_SUBMISSION_REQUIRED',
  'WITHDRAWAL_SUBMISSION_REQUIRED',
  'DELIVERY_MESSAGE_REQUESTED',
] as const;

export const INFORMATIONAL_OUTBOX_EVENT_TYPES = [
  'PRODUCT_PRICING_POLICY_CREATED',
  'AGENT_PRICING_OVERRIDE_CREATED',
  'AGENT_PRICING_OVERRIDE_CLOSED',
  'AGENT_RETAIL_PRICE_SET',
  'PAYMENT_INITIALIZATION_REQUESTED',
  'RESERVATION_EXPIRY_DUE',
] as const;

export type RedisOutboxEventType = (typeof REDIS_OUTBOX_EVENT_TYPES)[number];
